ediint-features: CEM
message-id: <20150413092732.2697.29003@Abhisheks-MacBook-Air.local>
content-length: 252
user-agent: PYAS2, A pythonic AS2 server
mime-version: 1.0
subject: EDI Message sent using pyas2
as2-to: pyas2win
accept-encoding: gzip, deflate, compress
accept: */*
content-transfer-encoding: base64
date: Mon, 13 Apr 2015 09:27:32 +0000
host: 192.168.1.112:8000
content-disposition: attachment; filename="smime.p7z"
recipient-address: http://192.168.1.112:8000/pyas2/as2receive
as2-from: pyas2mac
as2-version: 1.2
content-type: application/pkcs7-mime; name="smime.p7z"; smime-type="compressed-data"

MIAGCyqGSIb3DQEJEAEJoIAwgAIBADCABgsqhkiG9w0BCRADCAAAMIAGCSqGSIb3DQEHAaCABHd4
nC3MMQ6DMAyF4T1S7oDYafciJnqEDt2qEBywCLbVuEA4fVOp6/s/vZ5JgbR5ZIFb5UQieqfIdIUR
G8+USrWm/7M7JuGEP1C0qvPzWva2ChiB3ApdXT6AJiRYIF/00Gd+jXuorbFm+9CZ8jC8g3Dcj+0L
c08urQAAAAAAAAAAAAA=
