message-id: <20150413091925.9628.7217@hvraghuram-PC>
ediint-features: CEM
content-length: 544
content-transfer-encoding: base64
mime-version: 1.0
subject: EDI Message sent using pyas2
as2-to: pyas2mac
content-type: application/pkcs7-mime; name="smime.p7z"; smime-type="compressed-data"
date: Mon, 13 Apr 2015 14:49:25 +0530
host: 192.168.1.110:8000
connection: keep-alive
content-disposition: attachment; filename="smime.p7z"
accept: */*
as2-version: 1.2
as2-from: pyas2win
user-agent: PYAS2, A pythonic AS2 server
accept-encoding: gzip, deflate
recipient-address: http://192.168.1.110:8000/pyas2/as2receive

MIAGCyqGSIb3DQEJEAEJoIAwgAIBADCABgsqhkiG9w0BCRADCAAAMIAGCSqGSIb3DQEHAaCABIIB
TXictdFBS8MwFAfw+6DfIdSLHpblJc3WRjzMOq9KKV4lZHELtElJ0+kQv7uZGzLGDh5cLoH3f/Dj
zyudDdqGcb3ttECy6xqjZDDOTvTSjJWzfUyTUXlYezB953qzW4jbIUi1buP8Fr2ZRlvZ6rt0Pn/d
MMxw41ZdsK7N02SUjCiBjFBgY5gKyAUnmEGBSHxAigyN0aKqniqx/xAQwuMQkLGo9tJG1Ie6fKZC
VFouFx9SheubK7rLX7wQfrCvg02OmUJQJvgUs2y2Zyj/MwNnmNqXjYlVYzTY3ZAVp95MsBwzfqjF
5+VlPUZERjCl2Y9H7h+PPe+dR59ACZl9IafU4PUSva/jlVA8qtUqGLtCwaFe+432KF2H0InJxDdY
tu12i5VrU3QqguDwKwJAfk6kxf+JGcSaOCf00HFx4RtmVBCOIef7hoxcwPsGE5D1yQAAAAAAAAAA
AAA=
