# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyas2', '0013_auto_20160307_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='confirmation_message',
            field=models.CharField(blank=True, help_text='Use this field to send a customized message in the MDN Confirmations for this Organization', max_length=300, null=True, verbose_name='Confirmation Message'),
        ),
        migrations.AddField(
            model_name='partner',
            name='confirmation_message',
            field=models.CharField(blank=True, help_text='Use this field to send a customized message in the MDN Confirmations for this Partner', max_length=300, null=True, verbose_name='Confirmation Message'),
        ),
    ]
