# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-27 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import pyas2.models


class Migration(migrations.Migration):

    dependencies = [
        ('pyas2', '0018_auto_20180109_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdn',
            name='file',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='partner',
            name='https_ca_cert',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=pyas2.models.get_certificate_path, verbose_name='HTTPS Local CA Store'),
        ),
        migrations.AlterField(
            model_name='payload',
            name='file',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='privatecertificate',
            name='ca_cert',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=pyas2.models.get_certificate_path, verbose_name='Local CA Store'),
        ),
        migrations.AlterField(
            model_name='privatecertificate',
            name='certificate',
            field=models.FileField(max_length=500, upload_to=pyas2.models.get_certificate_path),
        ),
        migrations.AlterField(
            model_name='publiccertificate',
            name='ca_cert',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=pyas2.models.get_certificate_path, verbose_name='Local CA Store'),
        ),
        migrations.AlterField(
            model_name='publiccertificate',
            name='certificate',
            field=models.FileField(max_length=500, upload_to=pyas2.models.get_certificate_path),
        ),
    ]
