# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyas2', '0020_auto_20190315_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='content_type',
            field=models.CharField(choices=[(b'application/EDI-X12', b'application/EDI-X12'), (b'application/EDIFACT', b'application/EDIFACT'), (b'application/edi-consent', b'application/edi-consent'), (b'application/XML', b'application/XML'), (b'text/CSV', b'text/CSV')], default=b'application/edi-consent', max_length=100),
        ),
    ]